# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sassafras}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["T.J. VanSlyke"]
  s.date = %q{2009-11-17}
  s.default_executable = %q{sassafras}
  s.description = %q{Sass color scheme generator}
  s.email = %q{teejay.vanslyke@gmail.com}
  s.executables = ["sassafras"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
     "License.txt",
     "Manifest.txt",
     "PostInstall.txt",
     "README.txt",
     "Rakefile",
     "bin/sassafras",
     "config/hoe.rb",
     "config/requirements.rb",
     "examples/analogous_red.html",
     "examples/split_complementary_blue.html",
     "lib/sassafras.rb",
     "lib/sassafras/swatch.html.erb",
     "lib/sassafras/version.rb",
     "script/console",
     "script/destroy",
     "script/generate",
     "script/txt2html",
     "setup.rb",
     "spec/sassafras_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/deployment.rake",
     "tasks/environment.rake",
     "tasks/examples.rake",
     "tasks/rspec.rake",
     "tasks/website.rake",
     "website/index.html",
     "website/index.txt",
     "website/javascripts/rounded_corners_lite.inc.js",
     "website/stylesheets/screen.css",
     "website/template.html.erb"
  ]
  s.homepage = %q{http://github.com/teejayvanslyke/sassafras}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = nil
  s.test_files = [
    "spec/sassafras_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<color-tools>, [">= 1.3.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 1.3.0"])
    else
      s.add_dependency(%q<color-tools>, [">= 1.3.0"])
      s.add_dependency(%q<activesupport>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<color-tools>, [">= 1.3.0"])
    s.add_dependency(%q<activesupport>, [">= 1.3.0"])
  end
end
